"""
The DSH profile bundle that mounts this project's tools into the agent.

DeepSeek Harness composes its plugin tree from *patch layers*, and a patch entry
that carries an `id` **overrides** an existing row. A row list written in the
obvious shape

    - id: mcp-winvoice
      name: '@deepseek-ai/dsh-mcp-client'

therefore fails at boot with `patch: entry "mcp-winvoice" not found`, because
nothing by that id exists yet. Adding rows requires the `insert` wrapper:

    - insert:
        - id: mcp-winvoice
          name: '@deepseek-ai/dsh-mcp-client'

(Verified against `applyEntryPatches` in `@deepseek-ai/dsh-app-boot`, and
end-to-end with `dsh --profile sdk --dump-config`.)

A layer is contributed by an installed package whose manifest declares
`dsh.bundle.patch` pointing at its patch file, and which is listed in the
profile's `dsh.profile.bundles`. So this module writes that tiny package and
`scripts/install_dsh_bridge.py` installs it.

Why a bundle and not a `--patch` overlay: `--patch` is the *same* id-targeted
mechanism, so it cannot add a row either. The bundle layer is the supported way
for a project to contribute a row to its own DSH profile, and it keeps the user's
`~/.dsh` untouched — the bundle lives in this repository's `runtime/` and in a
`DSH_HOME` this project owns.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

from winvoice.logging import get_logger

logger = get_logger(__name__)

BUNDLE_DIRNAME = "dsh_bridge"
BUNDLE_PACKAGE_NAME = "winvoice-dsh-bridge"
PATCH_FILENAME = "cordis.patch.yml"

#: The MCP plugin row's id inside the composed DSH entry list.
ROW_ID = "mcp-winvoice"


def _yaml_scalar(value: str) -> str:
    """Single-quote a YAML scalar, escaping the quote itself."""
    return "'" + str(value).replace("'", "''") + "'"


def patch_text(
    workspace: Path,
    server_name: str,
    python_executable: str,
    tool_timeout_ms: int,
    utterance_file: Optional[Path] = None,
) -> str:
    """
    The bundle's patch layer, as YAML.

    `cwd` is the repository root because `config/config.yaml` and the `models/`
    tree are resolved relative to the working directory — the same constraint
    `run.ps1` exists to satisfy for the main process. The MCP server inherits
    that requirement.

    `utterance_file` is pinned into the child's environment when given, so the
    tier check reads the same in-flight utterance record the audio process
    wrote, however the two processes were started.
    """
    lines = [
        "# Generated by winvoice/dsh/bridge.py — do not edit by hand.",
        "#",
        "# `insert:` (no `id`) appends rows to the composed entry list; an entry",
        "# with an `id` would instead override an existing row and fail with",
        "# `entry ... not found`, since this row does not exist yet.",
        "- insert:",
        f"    - id: {ROW_ID}",
        "      name: '@deepseek-ai/dsh-mcp-client'",
        "      config:",
        f"        serverName: {_yaml_scalar(server_name)}",
        "        transport: stdio",
        f"        command: {_yaml_scalar(python_executable)}",
        "        args:",
        "          - '-m'",
        "          - 'winvoice.mcp_server'",
        f"        cwd: {_yaml_scalar(workspace.as_posix())}",
        f"        toolCallTimeoutMs: {int(tool_timeout_ms)}",
    ]
    if utterance_file is not None:
        lines += [
            "        env:",
            f"          WINVOICE_UTTERANCE_FILE: {_yaml_scalar(utterance_file.as_posix())}",
        ]
    return "\n".join(lines) + "\n"


def write_bundle(
    dest: Path,
    workspace: Path,
    server_name: str = "winvoice",
    python_executable: Optional[str] = None,
    tool_timeout_ms: int = 120_000,
    utterance_file: Optional[Path] = None,
) -> Path:
    """
    Write the bundle package into `dest` and return its directory.

    Rewritten on every call rather than merged: the manifest and the patch are
    both generated artifacts derived from configuration, and a stale generated
    file that disagrees with the config is the kind of thing that produces an
    afternoon of debugging.
    """
    dest.mkdir(parents=True, exist_ok=True)

    manifest = {
        "name": BUNDLE_PACKAGE_NAME,
        "version": "0.1.0",
        "private": True,
        "description": "Mounts the Windows Voice Assistant tool registry into DeepSeek Harness over MCP.",
        "dsh": {"bundle": {"patch": PATCH_FILENAME}},
    }
    (dest / "package.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    (dest / PATCH_FILENAME).write_text(
        patch_text(
            workspace=workspace,
            server_name=server_name,
            python_executable=python_executable or sys.executable,
            tool_timeout_ms=tool_timeout_ms,
            utterance_file=utterance_file,
        ),
        encoding="utf-8",
    )

    logger.info("dsh_bridge_bundle_written", path=str(dest), server=server_name)
    return dest


__all__ = [
    "BUNDLE_DIRNAME",
    "BUNDLE_PACKAGE_NAME",
    "PATCH_FILENAME",
    "ROW_ID",
    "patch_text",
    "write_bundle",
]
