#!/usr/bin/env python3
"""
Build WinVoice-Setup-<version>.exe: the onefile wizard with the runtime
payload bundled inside.

    python installer/build_installer.py            # builds payload first if missing

Run on the dev machine; requires PyInstaller (pip install pyinstaller).

The wizard's version is stamped into installer/wizard/core/_version.py at
build time (that file is generated — never edit or commit it). The update
checker compares the name of the release asset WinVoice-Setup-<version>.exe
against this stamp, so keep the naming convention.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

INSTALLER_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = INSTALLER_DIR.parent
sys.path.insert(0, str(INSTALLER_DIR))

from wizard.core import pins  # noqa: E402

DIST_DIR = INSTALLER_DIR / "_dist"
BUILD_DIR = INSTALLER_DIR / "_build"
PAYLOAD_PATH = INSTALLER_DIR / "payload" / "runtime.tar.xz"
ENTRY_SCRIPT = INSTALLER_DIR / "setup_entry.py"
VERSION_STAMP = INSTALLER_DIR / "wizard" / "core" / "_version.py"


def project_version() -> str:
    with open(PROJECT_ROOT / "pyproject.toml", "rb") as file:
        return tomllib.load(file)["project"]["version"]


def stamp_version(version: str) -> None:
    VERSION_STAMP.write_text(
        f'"""Generated by build_installer.py — do not edit or commit."""\n\n'
        f'VERSION = "{version}"\n',
        encoding="utf-8",
    )


def ensure_payload() -> None:
    if PAYLOAD_PATH.is_file():
        return
    print("[i] payload missing — building it first")
    run([sys.executable, INSTALLER_DIR / "build_runtime.py"])


def run(cmd: list) -> None:
    print(f"$ {' '.join(str(part) for part in cmd)}", flush=True)
    result = subprocess.run([str(part) for part in cmd])
    if result.returncode != 0:
        raise SystemExit(f"[X] command failed (exit {result.returncode}): {cmd}")


def main() -> int:
    version = project_version()
    name = f"WinVoice-Setup-{version}"
    stamp_version(version)
    ensure_payload()

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    run([
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--onefile", "--noconsole",
        "--name", name,
        "--paths", str(INSTALLER_DIR),
        # Windows add-data separator is ";".
        "--add-data", f"{PAYLOAD_PATH};payload",
        "--distpath", str(DIST_DIR),
        "--workpath", str(BUILD_DIR),
        "--specpath", str(BUILD_DIR),
        str(ENTRY_SCRIPT),
    ])

    exe = DIST_DIR / f"{name}.exe"
    if not exe.is_file():
        raise SystemExit("[X] PyInstaller reported success but the exe is missing")
    size_mb = exe.stat().st_size / (1024 * 1024)
    print(f"\n[OK] installer ready: {exe} ({size_mb:.0f} MB)")
    print("release assets: this exe; update checks read "
          f"{pins.UPDATE_API_URL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
