#!/usr/bin/env python3
"""
Build WinVoice-Setup-<version>.exe: the onefile wizard with the runtime
payload bundled inside.

    python installer/build_installer.py            # builds payload first if missing

Run on the dev machine; requires PyInstaller (pip install pyinstaller).

The wizard's version is stamped into installer/wizard/core/_version.py at
build time (that file is generated — never edit or commit it). The update
checker compares the name of the release asset WinVoice-Setup-<version>.exe
against this stamp, so keep the naming convention.

Two guards encode the release rules learned the hard way (UNIMPLEMENTED.md
§3): the version must agree between pyproject.toml and winvoice/__init__.py,
and it must not equal the newest already-published release — a same-numbered
rebuild is never offered to installed machines, because the on-wizard
comparison is strictly-greater. `--allow-same-version` overrides the second
guard after a deliberate decision. A WinVoice-Setup-<version>.exe.sha256
sidecar is written next to the exe and must be uploaded as a second release
asset — the wizard verifies it after downloading.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
import tomllib
from pathlib import Path

INSTALLER_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = INSTALLER_DIR.parent
sys.path.insert(0, str(INSTALLER_DIR))

from wizard.core import pins, update  # noqa: E402

DIST_DIR = INSTALLER_DIR / "_dist"
BUILD_DIR = INSTALLER_DIR / "_build"
PAYLOAD_PATH = INSTALLER_DIR / "payload" / "runtime.tar.xz"
ENTRY_SCRIPT = INSTALLER_DIR / "setup_entry.py"
VERSION_STAMP = INSTALLER_DIR / "wizard" / "core" / "_version.py"


def project_version() -> str:
    with open(PROJECT_ROOT / "pyproject.toml", "rb") as file:
        return tomllib.load(file)["project"]["version"]


def package_version() -> str:
    """`winvoice/__init__.py`'s `__version__`, read by regex — importing the
    package would drag sherpa-onnx & friends onto the build machine."""
    init = PROJECT_ROOT / "winvoice" / "__init__.py"
    match = re.search(r'^__version__\s*=\s*"([^"]+)"', init.read_text(encoding="utf-8"), re.M)
    if not match:
        raise SystemExit(f"[X] no __version__ string found in {init}")
    return match.group(1)


def published_version_or_none(timeout: float = 10.0) -> str | None:
    """
    Newest non-draft release version carrying a setup exe, or None when the
    check cannot run (offline, API hiccup) — a build must not hard-fail
    because the dev machine has no network, but the skip is announced loudly.
    """
    try:
        payload = update.fetch_release_pages(pins.UPDATE_API_URL, timeout)
    except Exception as exc:
        print(f"[!] 查询 GitHub Releases 失败（{exc}）——本次跳过同版本守卫，请自行确认版本号已递增")
        return None
    if not isinstance(payload, list):
        print("[!] GitHub Releases 返回了意外的结构——本次跳过同版本守卫")
        return None
    return update.newest_published_version(payload)


def stamp_version(version: str) -> None:
    VERSION_STAMP.write_text(
        f'"""Generated by build_installer.py — do not edit or commit."""\n\n'
        f'VERSION = "{version}"\n',
        encoding="utf-8",
    )


def write_sha256(exe: Path) -> Path:
    """Write the sha256sum-compatible sidecar next to the exe."""
    digest = hashlib.sha256()
    with exe.open("rb") as file:
        for chunk in iter(lambda: file.read(1 << 20), b""):
            digest.update(chunk)
    sidecar = exe.parent / f"{exe.name}.sha256"
    sidecar.write_text(f"{digest.hexdigest()}  {exe.name}\n", encoding="ascii")
    return sidecar


def ensure_payload() -> None:
    if PAYLOAD_PATH.is_file():
        return
    print("[i] payload missing — building it first")
    run([sys.executable, INSTALLER_DIR / "build_runtime.py"])


def run(cmd: list) -> None:
    print(f"$ {' '.join(str(part) for part in cmd)}", flush=True)
    result = subprocess.run([str(part) for part in cmd])
    if result.returncode != 0:
        raise SystemExit(f"[X] command failed (exit {result.returncode}): {cmd}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the WinVoice setup wizard")
    parser.add_argument(
        "--allow-same-version", action="store_true",
        help="build even when the newest published release already carries this "
             "version (the rebuild will never be offered to installed machines)",
    )
    args = parser.parse_args()

    version = project_version()
    in_package = package_version()
    if in_package != version:
        raise SystemExit(
            f"[X] 版本号不一致：pyproject.toml 是 {version}，"
            f"winvoice/__init__.py 是 {in_package}——两处都要 bump（发版记录 2026-09-28 的坑）"
        )
    published = published_version_or_none()
    if published is not None and published == version and not args.allow_same_version:
        raise SystemExit(
            f"[X] v{version} 已经是最新已发布版本——同号重打包对已安装的机器永远不可见\n"
            "    （更新比对是严格递增）。请先在 pyproject.toml 和\n"
            "    winvoice/__init__.py 两处 bump 版本，或确认无误后加 --allow-same-version。"
        )

    name = f"WinVoice-Setup-{version}"
    stamp_version(version)
    ensure_payload()

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    run([
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--onefile", "--noconsole",
        "--name", name,
        "--paths", str(INSTALLER_DIR),
        # Windows add-data separator is ";".
        "--add-data", f"{PAYLOAD_PATH};payload",
        "--distpath", str(DIST_DIR),
        "--workpath", str(BUILD_DIR),
        "--specpath", str(BUILD_DIR),
        str(ENTRY_SCRIPT),
    ])

    exe = DIST_DIR / f"{name}.exe"
    if not exe.is_file():
        raise SystemExit("[X] PyInstaller reported success but the exe is missing")
    sidecar = write_sha256(exe)
    size_mb = exe.stat().st_size / (1024 * 1024)
    print(f"\n[OK] installer ready: {exe} ({size_mb:.0f} MB)")
    print(f"[OK] checksum sidecar: {sidecar}")
    print(f"release assets: this exe as WinVoice-Setup-{version}.exe PLUS its .sha256 — "
          "upload both; the wizard lists releases (drafts skipped, pre-releases count) via "
          f"{pins.UPDATE_API_URL.replace('/releases/latest', '/releases')}")
    print("publish NOT as a pre-release while an already-installed older wizard "
          "must see it: that wizard still queries /releases/latest, which "
          "excludes pre-releases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
